package com.fanyank.mapper;

import com.fanyank.pojo.Folder;
import java.util.List;

public interface FolderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int insert(Folder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    Folder selectByPrimaryKey(Integer id);

    Folder selectByPrimaryKeyInPrivate(Integer id);

    Folder selectByPrimaryKeyInPublic(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    List<Folder> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table folder
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Folder record);

    /**
     * 获取根目录
     * @return
     */
    Folder getRootFolder();

    /**
     * 获取用户根目录
     * @param userId
     * @return
     */
    Folder getUserRootFolder(Integer userId);

    /**
     * 获取父目录下的所有子目录
     * @param preFolderId
     * @return
     */
    List<Folder> selectFolderListByPreFolderId(Integer preFolderId);
}